version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "1011:5173"
    volumes:
      - ./src:/app/src
    environment:
      - NODE_ENV=production 